
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OpenFrontKingSarcophagusFacingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7302, 2, 1, 0}, {7303, 1, 1, 0}, {7304, 0, 1, 0}// 1	2	3	
			, {7305, -1, 1, 0}, {7306, -2, 1, 0}, {7307, -2, 0, 0}// 4	5	6	
			, {7308, -1, 0, 0}, {7309, 0, 0, 0}, {7310, 1, 0, 0}// 7	8	9	
			, {7311, 2, 0, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OpenFrontKingSarcophagusFacingEastAddonDeed();
			}
		}

		[ Constructable ]
		public OpenFrontKingSarcophagusFacingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OpenFrontKingSarcophagusFacingEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OpenFrontKingSarcophagusFacingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OpenFrontKingSarcophagusFacingEastAddon();
			}
		}

		[Constructable]
		public OpenFrontKingSarcophagusFacingEastAddonDeed()
		{
			Name = "Open Front King Sarcophagus Facing East";
		}

		public OpenFrontKingSarcophagusFacingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}