
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OpenSideKingSarcophagusFacingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7296, 1, 0, 0}, {7297, 0, 0, 0}, {7298, -1, 0, 0}// 1	2	3	
			, {7299, -1, -1, 0}, {7300, 0, -1, 0}, {7301, 1, -1, 0}// 4	5	6	
			, {7293, -1, 1, 0}, {7294, 0, 1, 0}, {7295, 1, 1, 0}// 7	8	9	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OpenSideKingSarcophagusFacingEastAddonDeed();
			}
		}

		[ Constructable ]
		public OpenSideKingSarcophagusFacingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OpenSideKingSarcophagusFacingEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OpenSideKingSarcophagusFacingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OpenSideKingSarcophagusFacingEastAddon();
			}
		}

		[Constructable]
		public OpenSideKingSarcophagusFacingEastAddonDeed()
		{
			Name = "Open Side King Sarcophagus Facing East";
		}

		public OpenSideKingSarcophagusFacingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}