
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OpenSideQueenSarcophagusFacingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7270, -1, 1, 0}, {7271, 0, 1, 0}, {7272, 1, 1, 0}// 1	2	3	
			, {7273, 1, 0, 0}, {7274, 0, 0, 0}, {7275, -1, 0, 0}// 4	5	6	
			, {7276, -1, -1, 0}, {7277, 0, -1, 0}, {7278, 1, -1, 0}// 7	8	9	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OpenSideQueenSarcophagusFacingEastAddonDeed();
			}
		}

		[ Constructable ]
		public OpenSideQueenSarcophagusFacingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OpenSideQueenSarcophagusFacingEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OpenSideQueenSarcophagusFacingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OpenSideQueenSarcophagusFacingEastAddon();
			}
		}

		[Constructable]
		public OpenSideQueenSarcophagusFacingEastAddonDeed()
		{
			Name = "Open Side Queen Sarcophagus Facing East";
		}

		public OpenSideQueenSarcophagusFacingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}