
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OpenQueenSarcophagusFacingSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7318, 1, -1, 0}, {7319, 1, 0, 0}, {7320, 1, 1, 0}// 1	2	3	
			, {7321, 0, 1, 0}, {7322, 0, 0, 0}, {7323, 0, -1, 0}// 4	5	6	
			, {7324, -1, -1, 0}, {7325, -1, 0, 0}, {7326, -1, 1, 0}// 7	8	9	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OpenQueenSarcophagusFacingSouthAddonDeed();
			}
		}

		[ Constructable ]
		public OpenQueenSarcophagusFacingSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OpenQueenSarcophagusFacingSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OpenQueenSarcophagusFacingSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OpenQueenSarcophagusFacingSouthAddon();
			}
		}

		[Constructable]
		public OpenQueenSarcophagusFacingSouthAddonDeed()
		{
			Name = "Open Queen Sarcophagus Facing South";
		}

		public OpenQueenSarcophagusFacingSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}