
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OpenFrontKingSarcophagusFacingSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7359, 0, 2, 0}, {7358, 0, 1, 0}, {7357, 0, 0, 0}// 1	2	3	
			, {7354, 1, -1, 0}, {7355, 0, -1, 0}, {7356, 0, 0, 0}// 4	5	6	
			, {7353, 1, 0, 0}, {7352, 1, 1, 0}, {7351, 1, 2, 0}// 7	8	9	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OpenFrontKingSarcophagusFacingSouthAddonDeed();
			}
		}

		[ Constructable ]
		public OpenFrontKingSarcophagusFacingSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OpenFrontKingSarcophagusFacingSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OpenFrontKingSarcophagusFacingSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OpenFrontKingSarcophagusFacingSouthAddon();
			}
		}

		[Constructable]
		public OpenFrontKingSarcophagusFacingSouthAddonDeed()
		{
			Name = "Open Front King Sarcophagus Facing South";
		}

		public OpenFrontKingSarcophagusFacingSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}