
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SealedQueenSarcophagusFacingSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7312, 1, 1, 0}, {7313, 1, 0, 0}, {7314, 1, -1, 0}// 1	2	3	
			, {7315, 0, -1, 0}, {7316, 0, 0, 0}, {7317, 0, 1, 0}// 4	5	6	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SealedQueenSarcophagusFacingSouthAddonDeed();
			}
		}

		[ Constructable ]
		public SealedQueenSarcophagusFacingSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SealedQueenSarcophagusFacingSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SealedQueenSarcophagusFacingSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SealedQueenSarcophagusFacingSouthAddon();
			}
		}

		[Constructable]
		public SealedQueenSarcophagusFacingSouthAddonDeed()
		{
			Name = "Sealed Queen Sarcophagus Facing South";
		}

		public SealedQueenSarcophagusFacingSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}