
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CraneSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18920, 0, 1, 0}, {18921, 0, 0, 0}, {18922, 0, -1, 0}// 1	2	3	
			, {18924, 1, 0, 0}, {18925, -1, 0, 0}, {18926, 1, -1, 0}// 4	5	6	
			, {18927, 0, 2, 0}, {18923, 0, 3, 0}, {18928, 0, -2, 0}// 7	8	9	
			, {18929, -1, -1, 1}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CraneSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CraneSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CraneSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CraneSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CraneSouthAddon();
			}
		}

		[Constructable]
		public CraneSouthAddonDeed()
		{
			Name = "CraneSouth";
		}

		public CraneSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}