
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CraneWestAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18938, -2, 0, 0}, {18931, 1, 0, 0}, {18932, 2, 0, 0}// 1	2	3	
			, {18930, 0, 0, 0}, {18933, 3, 0, 0}, {18936, 2, 1, 0}// 4	5	6	
			, {18937, 1, 1, 0}, {18934, 2, -1, 0}, {18935, 1, -1, 0}// 7	8	9	
			, {18939, -1, 0, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CraneWestAddonDeed();
			}
		}

		[ Constructable ]
		public CraneWestAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CraneWestAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CraneWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CraneWestAddon();
			}
		}

		[Constructable]
		public CraneWestAddonDeed()
		{
			Name = "CraneWest";
		}

		public CraneWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}