
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CraneNorthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18910, 0, 0, 0}, {18919, 0, -1, 0}, {18918, 0, -2, 0}// 1	2	3	
			, {18912, 0, 2, 0}, {18911, 0, 1, 0}, {18913, 0, 3, 0}// 4	5	6	
			, {18914, 1, 2, 0}, {18915, 1, 1, 0}, {18917, -1, 1, 1}// 7	8	9	
			, {18916, -1, 2, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CraneNorthAddonDeed();
			}
		}

		[ Constructable ]
		public CraneNorthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CraneNorthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CraneNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CraneNorthAddon();
			}
		}

		[Constructable]
		public CraneNorthAddonDeed()
		{
			Name = "CraneNorth";
		}

		public CraneNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}