
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BallistaFacingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6384, 2, 0, 0}, {6386, 1, 0, 0}, {6400, 0, 1, 0}// 1	2	3	
			, {6402, -1, 0, 0}, {6399, 0, 0, 0}, {6401, 0, 2, 0}// 4	5	6	
			, {6397, 0, -2, 0}, {6385, 1, -1, 0}, {6398, 0, -1, 0}// 7	8	9	
			, {6387, 1, 1, 0}, {6396, -2, 0, 0}, {6406, 2, -1, 0}// 10	11	12	
			, {6411, 2, 1, 0}// 13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BallistaFacingEastAddonDeed();
			}
		}

		[ Constructable ]
		public BallistaFacingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public BallistaFacingEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BallistaFacingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BallistaFacingEastAddon();
			}
		}

		[Constructable]
		public BallistaFacingEastAddonDeed()
		{
			Name = "Ballista";
		}

		public BallistaFacingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}