
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BoxcarAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1206, -2, -2, 15}, {1206, -1, -4, 15}, {1206, -1, -7, 36}// 2	4	6	
			, {1206, -1, 0, 36}, {1206, -1, -5, 15}, {1206, -2, -3, 15}// 13	23	26	
			, {1206, -2, 2, 15}, {1206, -1, -6, 15}, {1206, -1, -3, 36}// 32	38	39	
			, {1206, -1, -7, 15}, {1206, -2, -4, 15}, {1206, -2, -1, 15}// 49	52	53	
			, {1206, -1, 1, 15}, {1206, -2, -6, 36}, {1206, -1, -6, 36}// 57	59	70	
			, {1206, -2, -5, 15}, {1206, -2, 0, 36}, {1206, -2, 1, 15}// 73	74	75	
			, {1206, -1, 2, 15}, {1206, -1, -4, 36}, {1206, -2, -4, 36}// 82	85	91	
			, {1206, -2, -6, 15}, {1206, -1, -1, 36}, {1206, -2, 0, 15}// 104	108	110	
			, {1206, -2, 1, 36}, {1206, -2, -7, 15}, {1206, -1, -2, 36}// 111	116	125	
			, {1206, -2, -1, 36}, {1206, -1, 2, 36}, {1206, -1, 1, 36}// 127	130	138	
			, {1206, -1, -1, 15}, {1206, -2, -3, 36}, {1206, -1, 0, 15}// 139	140	141	
			, {1206, -2, -7, 36}, {1206, -1, -2, 15}, {1206, -1, -5, 36}// 143	146	148	
			, {1206, -1, -3, 15}, {1206, -2, -5, 36}, {1206, -2, 2, 36}// 151	161	165	
			, {1206, -2, -2, 36}, {1206, -1, 8, 36}, {1206, -2, 8, 36}// 176	180	184	
			, {1206, -2, 7, 36}, {1206, -2, 4, 36}, {1206, -2, 3, 15}// 192	207	211	
			, {1206, -1, 6, 36}, {1206, -2, 8, 15}, {1206, -2, 3, 36}// 219	223	225	
			, {1206, -1, 3, 36}, {1206, -2, 7, 15}, {1206, -1, 8, 15}// 227	231	233	
			, {1206, -1, 7, 36}, {1206, -2, 6, 36}, {1206, -1, 5, 15}// 237	238	239	
			, {1206, -2, 6, 15}, {1206, -1, 4, 15}, {1206, -1, 5, 36}// 252	258	265	
			, {1206, -1, 7, 15}, {1206, -1, 4, 36}, {1206, -1, 3, 15}// 267	269	270	
			, {1206, -1, 6, 15}, {1206, -2, 4, 15}, {1206, -2, 5, 36}// 283	284	286	
			, {1206, -2, 5, 15}// 287	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BoxcarAddonDeed();
			}
		}

		[ Constructable ]
		public BoxcarAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1206, 0, -6, 15, 0, -1, "boxcar", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1206, 3, -2, 15, 1717, -1, "boxcar", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1206, 0, 1, 36, 0, -1, "boxcar", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1206, 2, 2, 36, 0, -1, "boxcar", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1206, 1, -5, 36, 0, -1, "boxcar", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1206, 3, -1, 15, 0, -1, "boxcar", 1);// 9
			AddComplexComponent( (BaseAddon) this, 155, -3, -6, 36, 1717, -1, "boxcar", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1206, 1, -1, 36, 0, -1, "boxcar", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1206, 1, 0, 15, 0, -1, "boxcar", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1206, 2, 2, 15, 0, -1, "boxcar", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1206, 3, -6, 36, 0, -1, "boxcar", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1206, 3, -7, 36, 0, -1, "boxcar", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1206, 3, 0, 15, 0, -1, "boxcar", 1);// 17
			AddComplexComponent( (BaseAddon) this, 156, 2, -8, 36, 1717, -1, "boxcar", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1206, 1, -1, 15, 0, -1, "boxcar", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1206, 2, 1, 15, 0, -1, "boxcar", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1206, 0, -2, 36, 0, -1, "boxcar", 1);// 21
			AddComplexComponent( (BaseAddon) this, 146, 0, -8, 15, 1717, -1, "boxcar", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1206, 0, -4, 36, 0, -1, "boxcar", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1206, 1, -2, 15, 0, -1, "boxcar", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1206, 1, -4, 36, 0, -1, "boxcar", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1206, 0, -3, 15, 0, -1, "boxcar", 1);// 28
			AddComplexComponent( (BaseAddon) this, 155, -3, -4, 36, 1717, -1, "boxcar", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1206, 2, 1, 15, 0, -1, "boxcar", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1206, 2, -5, 36, 0, -1, "boxcar", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1206, 0, 0, 36, 0, -1, "boxcar", 1);// 33
			AddComplexComponent( (BaseAddon) this, 155, -3, -5, 36, 1717, -1, "boxcar", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1206, 0, -7, 36, 0, -1, "boxcar", 1);// 35
			AddComplexComponent( (BaseAddon) this, 146, 2, -8, 15, 1717, -1, "boxcar", 1);// 36
			AddComplexComponent( (BaseAddon) this, 3693, 2, -6, 0, 2401, -1, "boxcar", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1206, 2, -3, 36, 0, -1, "boxcar", 1);// 40
			AddComplexComponent( (BaseAddon) this, 155, 3, -6, 36, 1717, -1, "boxcar", 1);// 41
			AddComplexComponent( (BaseAddon) this, 146, 1, -8, 15, 1717, -1, "boxcar", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1206, 3, 1, 36, 0, -1, "boxcar", 1);// 43
			AddComplexComponent( (BaseAddon) this, 145, 3, 2, 15, 1717, -1, "boxcar", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1206, 0, -6, 36, 0, -1, "boxcar", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1206, 1, -3, 15, 0, -1, "boxcar", 1);// 46
			AddComplexComponent( (BaseAddon) this, 155, 3, -7, 36, 1717, -1, "boxcar", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1206, 3, -7, 15, 0, -1, "boxcar", 1);// 48
			AddComplexComponent( (BaseAddon) this, 146, -2, -8, 15, 1717, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1206, 2, -1, 15, 0, -1, "boxcar", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1206, 0, -5, 36, 0, -1, "boxcar", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1206, 2, 0, 36, 0, -1, "boxcar", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1206, 2, 1, 36, 0, -1, "boxcar", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1206, 0, -2, 15, 0, -1, "boxcar", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1206, 0, 2, 15, 0, -1, "boxcar", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1206, 0, -7, 15, 0, -1, "boxcar", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1206, 0, 1, 15, 0, -1, "boxcar", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1206, 1, -3, 36, 0, -1, "boxcar", 1);// 63
			AddComplexComponent( (BaseAddon) this, 151, 3, -8, 15, 1717, -1, "boxcar", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1206, 2, 0, 15, 0, -1, "boxcar", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1206, 1, 1, 15, 0, -1, "boxcar", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1206, 1, 0, 36, 0, -1, "boxcar", 1);// 67
			AddComplexComponent( (BaseAddon) this, 145, -3, 2, 15, 1717, -1, "boxcar", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1206, 0, -1, 36, 0, -1, "boxcar", 1);// 69
			AddComplexComponent( (BaseAddon) this, 155, -3, -1, 36, 1717, -1, "boxcar", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1206, 1, -6, 15, 0, -1, "boxcar", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1206, 3, 0, 36, 0, -1, "boxcar", 1);// 76
			AddComplexComponent( (BaseAddon) this, 155, 3, 0, 36, 1717, -1, "boxcar", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1206, 2, -4, 36, 0, -1, "boxcar", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1206, 3, -5, 36, 0, -1, "boxcar", 1);// 79
			AddComplexComponent( (BaseAddon) this, 145, 3, -3, 15, 1717, -1, "boxcar", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1206, 3, -6, 15, 0, -1, "boxcar", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1206, 2, -6, 36, 0, -1, "boxcar", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1206, 2, -7, 36, 0, -1, "boxcar", 1);// 84
			AddComplexComponent( (BaseAddon) this, 3693, 2, -4, 0, 2401, -1, "boxcar", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1206, 1, -7, 15, 0, -1, "boxcar", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1206, 3, 1, 15, 0, -1, "boxcar", 1);// 88
			AddComplexComponent( (BaseAddon) this, 155, 3, 2, 36, 1717, -1, "boxcar", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1206, 1, 2, 15, 0, -1, "boxcar", 1);// 90
			AddComplexComponent( (BaseAddon) this, 145, -3, 1, 15, 1717, -1, "boxcar", 1);// 92
			AddComplexComponent( (BaseAddon) this, 145, 3, -2, 15, 1717, -1, "boxcar", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1206, 2, 2, 15, 0, -1, "boxcar", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1206, 2, -1, 36, 0, -1, "boxcar", 1);// 95
			AddComplexComponent( (BaseAddon) this, 147, -3, -8, 15, 1717, -1, "boxcar", 1);// 96
			AddComplexComponent( (BaseAddon) this, 145, 3, 1, 15, 1717, -1, "boxcar", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1206, 3, 2, 15, 0, -1, "boxcar", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1206, 0, -4, 15, 0, -1, "boxcar", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1206, 0, -5, 15, 0, -1, "boxcar", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1206, 0, 0, 15, 0, -1, "boxcar", 1);// 101
			AddComplexComponent( (BaseAddon) this, 155, 3, -5, 36, 1717, -1, "boxcar", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1206, 0, -3, 36, 0, -1, "boxcar", 1);// 103
			AddComplexComponent( (BaseAddon) this, 155, -3, 2, 36, 1717, -1, "boxcar", 1);// 105
			AddComplexComponent( (BaseAddon) this, 156, -2, -8, 36, 1717, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1206, 3, -2, 36, 1717, -1, "boxcar", 1);// 107
			AddComplexComponent( (BaseAddon) this, 156, 0, -8, 36, 1717, -1, "boxcar", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1206, 1, -7, 36, 0, -1, "boxcar", 1);// 112
			AddComplexComponent( (BaseAddon) this, 155, -3, 1, 36, 1717, -1, "boxcar", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1206, 1, 1, 36, 0, -1, "boxcar", 1);// 114
			AddComplexComponent( (BaseAddon) this, 156, 1, -8, 36, 1717, -1, "boxcar", 1);// 115
			AddComplexComponent( (BaseAddon) this, 155, 3, -1, 36, 1717, -1, "boxcar", 1);// 117
			AddComplexComponent( (BaseAddon) this, 145, -3, -4, 15, 1717, -1, "boxcar", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1206, 0, -1, 15, 0, -1, "boxcar", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1206, 2, -2, 36, 0, -1, "boxcar", 1);// 120
			AddComplexComponent( (BaseAddon) this, 155, 3, -3, 36, 1717, -1, "boxcar", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1206, 2, -1, 15, 0, -1, "boxcar", 1);// 122
			AddComplexComponent( (BaseAddon) this, 157, -3, -8, 36, 1717, -1, "boxcar", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1206, 1, 2, 36, 0, -1, "boxcar", 1);// 124
			AddComplexComponent( (BaseAddon) this, 146, -1, -8, 15, 1717, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 156, -1, -8, 36, 1717, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 145, 3, -5, 15, 1717, -1, "boxcar", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1206, 3, -3, 36, 1717, -1, "boxcar", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1206, 1, -5, 15, 0, -1, "boxcar", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1206, 2, -7, 15, 0, -1, "boxcar", 1);// 133
			AddComplexComponent( (BaseAddon) this, 155, -3, -7, 36, 1717, -1, "boxcar", 1);// 134
			AddComplexComponent( (BaseAddon) this, 145, 3, -4, 15, 1717, -1, "boxcar", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1206, 3, -1, 36, 0, -1, "boxcar", 1);// 136
			AddComplexComponent( (BaseAddon) this, 155, -3, -2, 36, 1717, -1, "boxcar", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1206, 3, -4, 36, 0, -1, "boxcar", 1);// 142
			AddComplexComponent( (BaseAddon) this, 155, 3, 1, 36, 1717, -1, "boxcar", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1206, 2, -4, 15, 0, -1, "boxcar", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1206, 1, -4, 15, 0, -1, "boxcar", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1206, 1, -2, 36, 0, -1, "boxcar", 1);// 149
			AddComplexComponent( (BaseAddon) this, 161, 3, -8, 36, 1717, -1, "boxcar", 1);// 150
			AddComplexComponent( (BaseAddon) this, 145, -3, -3, 15, 1717, -1, "boxcar", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1206, 2, -3, 15, 0, -1, "boxcar", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1206, 3, -3, 15, 1717, -1, "boxcar", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1206, 2, -5, 15, 0, -1, "boxcar", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1206, 1, -6, 36, 0, -1, "boxcar", 1);// 156
			AddComplexComponent( (BaseAddon) this, 155, -3, -3, 36, 1717, -1, "boxcar", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1206, 2, -6, 15, 0, -1, "boxcar", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1206, 3, 2, 36, 0, -1, "boxcar", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1206, 3, -5, 15, 0, -1, "boxcar", 1);// 160
			AddComplexComponent( (BaseAddon) this, 155, -3, 0, 36, 1717, -1, "boxcar", 1);// 162
			AddComplexComponent( (BaseAddon) this, 155, 3, -2, 36, 1717, -1, "boxcar", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1206, 0, 2, 36, 0, -1, "boxcar", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1206, 2, 0, 15, 0, -1, "boxcar", 1);// 166
			AddComplexComponent( (BaseAddon) this, 145, -3, -5, 15, 1717, -1, "boxcar", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1206, 3, -4, 15, 0, -1, "boxcar", 1);// 168
			AddComplexComponent( (BaseAddon) this, 155, 3, -4, 36, 1717, -1, "boxcar", 1);// 169
			AddComplexComponent( (BaseAddon) this, 145, -3, -7, 15, 1717, -1, "boxcar", 1);// 170
			AddComplexComponent( (BaseAddon) this, 145, -3, -6, 15, 1717, -1, "boxcar", 1);// 171
			AddComplexComponent( (BaseAddon) this, 145, 3, -7, 15, 1717, -1, "boxcar", 1);// 172
			AddComplexComponent( (BaseAddon) this, 145, 3, -6, 15, 1717, -1, "boxcar", 1);// 173
			AddComplexComponent( (BaseAddon) this, 145, -3, -2, 15, 1717, -1, "boxcar", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1206, 2, -2, 15, 0, -1, "boxcar", 1);// 175
			AddComplexComponent( (BaseAddon) this, 155, -3, 6, 36, 1717, -1, "boxcar", 1);// 177
			AddComplexComponent( (BaseAddon) this, 145, 3, 5, 15, 1717, -1, "boxcar", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1206, 0, 5, 15, 0, -1, "boxcar", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1206, 1, 4, 36, 0, -1, "boxcar", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1206, 0, 6, 36, 0, -1, "boxcar", 1);// 182
			AddComplexComponent( (BaseAddon) this, 155, 3, 5, 36, 1717, -1, "boxcar", 1);// 183
			AddComplexComponent( (BaseAddon) this, 155, -3, 5, 36, 1717, -1, "boxcar", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1206, 3, 7, 36, 0, -1, "boxcar", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1206, 0, 8, 15, 0, -1, "boxcar", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1206, 2, 3, 15, 0, -1, "boxcar", 1);// 188
			AddComplexComponent( (BaseAddon) this, 155, -3, 3, 36, 1717, -1, "boxcar", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1206, 3, 5, 36, 0, -1, "boxcar", 1);// 190
			AddComplexComponent( (BaseAddon) this, 155, 3, 3, 36, 1717, -1, "boxcar", 1);// 191
			AddComplexComponent( (BaseAddon) this, 160, -3, 8, 36, 1717, -1, "boxcar", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1206, 3, 5, 15, 0, -1, "boxcar", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1206, 2, 3, 15, 0, -1, "boxcar", 1);// 195
			AddComplexComponent( (BaseAddon) this, 146, -2, 8, 15, 1717, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 146, 0, 8, 15, 1717, -1, "boxcar", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1206, 1, 8, 36, 0, -1, "boxcar", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1206, 0, 3, 15, 0, -1, "boxcar", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1206, 1, 4, 15, 0, -1, "boxcar", 1);// 200
			AddComplexComponent( (BaseAddon) this, 155, -3, 4, 36, 1717, -1, "boxcar", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1206, 2, 6, 15, 0, -1, "boxcar", 1);// 202
			AddComplexComponent( (BaseAddon) this, 145, -3, 6, 15, 1717, -1, "boxcar", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1206, 0, 3, 36, 0, -1, "boxcar", 1);// 204
			AddComplexComponent( (BaseAddon) this, 156, 0, 8, 36, 1717, -1, "boxcar", 1);// 205
			AddComplexComponent( (BaseAddon) this, 146, -1, 8, 15, 1717, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 6262, 0, 9, 16, 1717, -1, "train car coupling", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1206, 0, 4, 36, 0, -1, "boxcar", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1206, 2, 8, 36, 0, -1, "boxcar", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1206, 0, 7, 15, 0, -1, "boxcar", 1);// 212
			AddComplexComponent( (BaseAddon) this, 145, 3, 4, 15, 1717, -1, "boxcar", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1206, 0, 4, 15, 0, -1, "boxcar", 1);// 214
			AddComplexComponent( (BaseAddon) this, 150, -3, 8, 15, 1717, -1, "boxcar", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1206, 1, 6, 36, 0, -1, "boxcar", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1206, 2, 8, 15, 0, -1, "boxcar", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1206, 2, 7, 15, 0, -1, "boxcar", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1206, 2, 6, 15, 0, -1, "boxcar", 1);// 220
			AddComplexComponent( (BaseAddon) this, 156, 1, 8, 36, 1717, -1, "boxcar", 1);// 221
			AddComplexComponent( (BaseAddon) this, 3693, 2, 6, 0, 2401, -1, "boxcar", 1);// 222
			AddComplexComponent( (BaseAddon) this, 144, 3, 8, 15, 1717, -1, "boxcar", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1206, 2, 5, 36, 0, -1, "boxcar", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1206, 1, 3, 15, 0, -1, "boxcar", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1206, 2, 4, 15, 0, -1, "boxcar", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1206, 3, 4, 15, 0, -1, "boxcar", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1206, 0, 5, 36, 0, -1, "boxcar", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1206, 2, 5, 15, 0, -1, "boxcar", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1206, 0, 7, 36, 0, -1, "boxcar", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1206, 1, 5, 36, 0, -1, "boxcar", 1);// 236
			AddComplexComponent( (BaseAddon) this, 155, 3, 6, 36, 1717, -1, "boxcar", 1);// 240
			AddComplexComponent( (BaseAddon) this, 156, 2, 8, 36, 1717, -1, "boxcar", 1);// 241
			AddComplexComponent( (BaseAddon) this, 145, -3, 7, 15, 1717, -1, "boxcar", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1206, 2, 7, 36, 0, -1, "boxcar", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1206, 0, 6, 15, 0, -1, "boxcar", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1206, 1, 7, 15, 0, -1, "boxcar", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1206, 3, 6, 15, 0, -1, "boxcar", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1206, 1, 7, 36, 0, -1, "boxcar", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1206, 2, 5, 15, 0, -1, "boxcar", 1);// 248
			AddComplexComponent( (BaseAddon) this, 145, -3, 5, 15, 1717, -1, "boxcar", 1);// 249
			AddComplexComponent( (BaseAddon) this, 145, 3, 6, 15, 1717, -1, "boxcar", 1);// 250
			AddComplexComponent( (BaseAddon) this, 156, -2, 8, 36, 1717, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 156, -1, 8, 36, 1717, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1206, 3, 3, 15, 0, -1, "boxcar", 1);// 254
			AddComplexComponent( (BaseAddon) this, 155, 3, 4, 36, 1717, -1, "boxcar", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1206, 1, 8, 15, 0, -1, "boxcar", 1);// 256
			AddComplexComponent( (BaseAddon) this, 145, -3, 3, 15, 1717, -1, "boxcar", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1206, 1, 5, 15, 0, -1, "boxcar", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1206, 3, 8, 15, 0, -1, "boxcar", 1);// 260
			AddComplexComponent( (BaseAddon) this, 146, 2, 8, 15, 1717, -1, "boxcar", 1);// 261
			AddComplexComponent( (BaseAddon) this, 146, 1, 8, 15, 1717, -1, "boxcar", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1206, 1, 3, 36, 0, -1, "boxcar", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1206, 1, 6, 15, 0, -1, "boxcar", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1206, 3, 4, 36, 0, -1, "boxcar", 1);// 266
			AddComplexComponent( (BaseAddon) this, 1206, 0, 8, 36, 0, -1, "boxcar", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1206, 3, 3, 36, 0, -1, "boxcar", 1);// 271
			AddComplexComponent( (BaseAddon) this, 155, 3, 7, 36, 1717, -1, "boxcar", 1);// 272
			AddComplexComponent( (BaseAddon) this, 1206, 3, 6, 36, 0, -1, "boxcar", 1);// 273
			AddComplexComponent( (BaseAddon) this, 416, -1, 9, 0, 1726, -1, "train car coupling", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1206, 3, 7, 15, 0, -1, "boxcar", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1206, 2, 8, 15, 0, -1, "boxcar", 1);// 276
			AddComplexComponent( (BaseAddon) this, 145, -3, 4, 15, 1717, -1, "boxcar", 1);// 277
			AddComplexComponent( (BaseAddon) this, 1206, 3, 8, 36, 0, -1, "boxcar", 1);// 278
			AddComplexComponent( (BaseAddon) this, 154, 3, 8, 36, 1717, -1, "boxcar", 1);// 279
			AddComplexComponent( (BaseAddon) this, 3693, 2, 4, 0, 2401, -1, "boxcar", 1);// 280
			AddComplexComponent( (BaseAddon) this, 1206, 2, 4, 15, 0, -1, "boxcar", 1);// 281
			AddComplexComponent( (BaseAddon) this, 155, -3, 7, 36, 1717, -1, "boxcar", 1);// 282
			AddComplexComponent( (BaseAddon) this, 1206, 2, 7, 15, 0, -1, "boxcar", 1);// 285
			AddComplexComponent( (BaseAddon) this, 145, 3, 3, 15, 1717, -1, "boxcar", 1);// 288
			AddComplexComponent( (BaseAddon) this, 145, 3, 7, 15, 1717, -1, "boxcar", 1);// 289
			AddComplexComponent( (BaseAddon) this, 1206, 2, 3, 36, 0, -1, "boxcar", 1);// 290
			AddComplexComponent( (BaseAddon) this, 1206, 2, 6, 36, 0, -1, "boxcar", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1206, 2, 4, 36, 0, -1, "boxcar", 1);// 292

		}

		public BoxcarAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BoxcarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BoxcarAddon();
			}
		}

		[Constructable]
		public BoxcarAddonDeed()
		{
			Name = "Boxcar";
		}

		public BoxcarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}