/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_catapultnorthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_catapultnorthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_catapultnorthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 5704 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 5705 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 5708 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 5709 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 5710 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 5711 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 5716 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 5721 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 5726 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 5731 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 5746 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 5785 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 5787 );
			AddComponent( ac, 1, 2, 3 );
			ac = new AddonComponent( 5709 );
			AddComponent( ac, 0, 1, 2 );

		}

		public AG_catapultnorthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_catapultnorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_catapultnorthAddon();
			}
		}

		[Constructable]
		public AG_catapultnorthAddonDeed()
		{
			Name = "AG_catapultnorth";
		}

		public AG_catapultnorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}