/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_catapulteastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_catapulteastAddonDeed();
			}
		}

		[ Constructable ]
		public AG_catapulteastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 5846 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 5845 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 5840 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 5835 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 5830 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 5821 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 5820 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 5819 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 5818 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 5817 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 5746 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 5822 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 5823 );
			AddComponent( ac, -2, -1, 0 );

		}

		public AG_catapulteastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_catapulteastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_catapulteastAddon();
			}
		}

		[Constructable]
		public AG_catapulteastAddonDeed()
		{
			Name = "AG_catapulteast";
		}

		public AG_catapulteastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}