
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class EvilLighthouseAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EvilLighthouseAddonDeed();
			}
		}

		[ Constructable ]
		public EvilLighthouseAddon()
		{



			AddComplexComponent( (BaseAddon) this, 6862, -2, -2, 0, 2075, -1, "beacon of the damned", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6846, -2, 0, 0, 2075, -1, "beacon of the damned", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6861, -2, -1, 0, 2075, -1, "beacon of the damned", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6845, -3, -1, 0, 2075, -1, "beacon of the damned", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6849, -2, 1, 0, 2075, -1, "beacon of the damned", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6843, -3, -3, 0, 2075, -1, "beacon of the damned", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6844, -3, -2, 0, 2075, -1, "beacon of the damned", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6842, -2, -3, 0, 2075, -1, "beacon of the damned", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6828, 3, -1, 0, 2075, -1, "beacon of the damned", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6825, 3, 2, 0, 2075, -1, "beacon of the damned", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6858, -1, 0, 0, 2075, -1, "beacon of the damned", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6863, -1, -2, 0, 2075, -1, "beacon of the damned", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6829, 2, -1, 0, 2075, -1, "beacon of the damned", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6860, 0, -1, 0, 2075, -1, "beacon of the damned", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6859, -1, -1, 0, 2075, -1, "beacon of the damned", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6864, 2, 2, 0, 2075, 0, "beacon of the damned", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6826, 3, 1, 0, 2075, -1, "beacon of the damned", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6838, 0, -2, 0, 2075, -1, "beacon of the damned", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6852, -1, 2, 0, 2075, -1, "beacon of the damned", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6832, 1, -1, 0, 2075, -1, "beacon of the damned", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6855, -1, 1, 0, 2075, -1, "beacon of the damned", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6835, 1, -2, 0, 2075, -1, "beacon of the damned", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6841, -1, -3, 0, 2075, -1, "beacon of the damned", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6827, 3, 0, 0, 2075, -1, "beacon of the damned", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6822, 1, 3, 0, 2075, -1, "beacon of the damned", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6823, 2, 3, 0, 2075, -1, "beacon of the damned", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6820, -1, 3, 0, 2075, -1, "beacon of the damned", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6821, 0, 3, 0, 2075, -1, "beacon of the damned", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6824, 3, 3, 0, 2075, -1, "beacon of the damned", 1);// 29

		}

		public EvilLighthouseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EvilLighthouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EvilLighthouseAddon();
			}
		}

		[Constructable]
		public EvilLighthouseAddonDeed()
		{
			Name = "EvilLighthouse";
		}

		public EvilLighthouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}