
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargePileofGarbageAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7076, -2, 0, 0}, {7077, -2, -1, 0}, {7081, -1, -2, 0}// 1	2	3	
			, {7082, 0, -2, 0}, {7085, 1, -2, 0}, {7084, 1, -1, 0}// 4	5	6	
			, {7083, 0, -1, 0}, {7080, -1, -1, 0}, {7079, -1, 0, 0}// 7	8	9	
			, {7071, 1, 2, 0}, {7072, 0, 2, 0}, {7073, -1, 2, 0}// 10	11	12	
			, {7074, -2, 2, 0}, {7075, -2, 1, 0}, {7090, 1, 1, 0}// 13	14	15	
			, {7078, -1, 1, 0}, {7087, 2, -1, 0}, {7088, 2, 0, 0}// 16	17	18	
			, {7086, 2, -2, 0}, {7089, 2, 1, 0}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargePileofGarbageAddonDeed();
			}
		}

		[ Constructable ]
		public LargePileofGarbageAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LargePileofGarbageAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargePileofGarbageAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargePileofGarbageAddon();
			}
		}

		[Constructable]
		public LargePileofGarbageAddonDeed()
		{
			Name = "Pile of Garbage";
		}

		public LargePileofGarbageAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}