
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargePileofWoodAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7059, 1, 1, 0}, {7058, 1, -1, 0}, {7057, 0, -1, 0}// 1	2	3	
			, {7049, 0, -2, 0}, {7047, -1, -2, 0}, {7056, -1, -1, 0}// 4	5	6	
			, {7048, -2, -1, 0}, {7046, -2, 0, 0}, {7055, -1, 0, 0}// 7	8	9	
			, {7054, -1, 1, 0}, {7045, -2, 1, 0}, {7050, 1, -2, 0}// 10	11	12	
			, {7043, -1, 2, 0}, {7044, -2, 2, 0}, {7042, 0, 2, 0}// 13	14	15	
			, {7041, 1, 2, 0}, {7052, 2, 0, 0}, {7051, 2, -1, 0}// 16	17	18	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargePileofWoodAddonDeed();
			}
		}

		[ Constructable ]
		public LargePileofWoodAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LargePileofWoodAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargePileofWoodAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargePileofWoodAddon();
			}
		}

		[Constructable]
		public LargePileofWoodAddonDeed()
		{
			Name = "Pile of Wood";
		}

		public LargePileofWoodAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}