
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class lighthouseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6825, 3, 2, 0}, {6826, 3, 1, 0}, {6827, 3, 0, 0}// 1	2	3	
			, {6828, 3, -1, 0}, {6829, 2, -1, 0}, {6832, 1, -1, 0}// 4	5	6	
			, {6835, 1, -2, 0}, {6838, 0, -2, 0}, {6846, -2, 0, 0}// 7	8	9	
			, {6849, -2, 1, 0}, {6852, -1, 2, 0}, {6855, -1, 1, 0}// 10	11	12	
			, {6858, -1, 0, 0}, {6860, 0, -1, 0}, {6859, -1, -1, 0}// 14	15	16	
			, {6861, -2, -1, 0}, {6863, -1, -2, 0}, {6843, -3, -3, 0}// 17	18	19	
			, {6862, -2, -2, 0}, {6844, -3, -2, 0}, {6842, -2, -3, 0}// 20	21	22	
			, {6841, -1, -3, 0}, {6845, -3, -1, 0}, {6820, -1, 3, 0}// 23	24	25	
			, {6821, 0, 3, 0}, {6822, 1, 3, 0}, {6823, 2, 3, 0}// 26	27	28	
			, {6824, 3, 3, 0}// 29	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new lighthouseAddonDeed();
			}
		}

		[ Constructable ]
		public lighthouseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6864, 2, 2, 0, 0, 0, "", 1);// 13

		}

		public lighthouseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class lighthouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new lighthouseAddon();
			}
		}

		[Constructable]
		public lighthouseAddonDeed()
		{
			Name = "lighthouse";
		}

		public lighthouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}