
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class newshutAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1848, 1, 4, 0}, {1848, 1, 3, 0}, {1848, 1, 2, 0}// 1	2	3	
			, {1848, 1, 1, 0}, {1848, 1, -1, 0}, {1848, 1, 0, 0}// 4	5	6	
			, {1848, 1, -2, 0}, {1848, 1, -3, 0}, {1863, 2, -4, 0}// 7	8	9	
			, {1848, -1, -3, 0}, {1848, -1, -2, 0}, {1848, -1, -1, 0}// 10	11	12	
			, {1848, -1, 0, 0}, {1848, -1, 1, 0}, {1848, -1, 2, 0}// 13	14	15	
			, {1848, -1, 3, 0}, {1848, -1, 4, 0}, {1848, 0, -3, 0}// 16	17	18	
			, {1848, 0, -2, 0}, {1848, 0, -1, 0}, {1848, 0, 0, 0}// 19	20	21	
			, {1848, 0, 1, 0}, {1848, 0, 2, 0}, {1848, 0, 3, 0}// 22	23	24	
			, {1848, 0, 4, 0}, {1864, -2, -4, 0}, {1850, 2, 4, 0}// 25	26	27	
			, {1850, 2, 3, 0}, {1850, 2, 2, 0}, {1850, 2, 1, 0}// 28	29	30	
			, {1850, 2, 0, 0}, {1850, 2, -1, 0}, {1850, 2, -2, 0}// 31	32	33	
			, {1850, 2, -3, 0}, {1851, -1, -4, 0}, {1851, 0, -4, 0}// 34	35	36	
			, {1851, 1, -4, 0}, {1852, -2, -3, 0}, {1852, -2, -2, 0}// 37	38	39	
			, {1852, -2, -1, 0}, {1852, -2, 0, 0}, {1852, -2, 1, 0}// 40	41	42	
			, {1852, -2, 2, 0}, {1852, -2, 3, 0}, {1852, -2, 4, 0}// 43	44	45	
			, {147, -1, -3, 5}, {147, 1, -3, 5}, {147, -1, 4, 5}// 46	47	48	
			, {147, 1, 4, 5}, {9959, -2, -4, 25}, {9959, -1, -3, 28}// 49	50	51	
			, {9961, 2, -4, 25}, {9961, 1, -3, 28}, {9958, 1, 4, 28}// 52	53	54	
			, {9960, -1, 4, 28}, {9948, -2, -3, 25}, {9948, -2, -2, 25}// 55	56	57	
			, {9948, -2, -1, 25}, {9948, -2, 0, 25}, {9948, -2, 1, 25}// 58	59	60	
			, {9948, -2, 2, 25}, {9948, -2, 3, 25}, {9948, -2, 4, 25}// 61	62	63	
			, {9964, -1, -4, 25}, {9964, 0, -4, 25}, {9964, 1, -4, 25}// 64	65	66	
			, {9964, 0, -3, 28}, {9946, 0, -2, 32}, {9946, 0, 3, 32}// 67	68	69	
			, {9946, 0, 2, 32}, {9946, 0, 1, 32}, {9946, 0, 0, 32}// 70	71	72	
			, {9946, 0, -1, 32}, {9948, -1, -2, 28}, {9948, -1, -1, 28}// 73	74	75	
			, {9948, -1, 0, 28}, {9948, -1, 1, 28}, {9948, -1, 2, 28}// 76	77	78	
			, {9948, -1, 3, 28}, {9947, 1, -2, 28}, {9947, 2, -3, 25}// 79	80	81	
			, {9947, 2, -2, 25}, {9947, 2, -1, 25}, {9947, 1, -1, 28}// 82	83	84	
			, {9947, 1, 0, 28}, {9947, 2, 0, 25}, {9947, 2, 1, 25}// 85	86	87	
			, {9947, 1, 1, 28}, {9947, 1, 2, 28}, {9947, 2, 2, 25}// 88	89	90	
			, {9947, 1, 3, 28}, {9947, 2, 3, 25}, {9947, 2, 4, 25}// 91	92	93	
			, {9963, 0, 4, 30}, {1862, -2, 5, 0}, {1861, 2, 5, 0}// 94	95	96	
			, {1849, -1, 5, 0}, {1849, 0, 5, 0}, {1849, 1, 5, 0}// 97	98	99	
			, {9958, 2, 5, 25}, {9960, -2, 5, 25}, {9963, 0, 5, 25}// 100	101	102	
			, {9963, -1, 5, 25}, {9963, 1, 5, 25}// 103	104	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new newshutAddonDeed();
			}
		}

		[ Constructable ]
		public newshutAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public newshutAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class newshutAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new newshutAddon();
			}
		}

		[Constructable]
		public newshutAddonDeed()
		{
			Name = "newshut";
		}

		public newshutAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}