
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RoyalCarriageAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1206, 0, 1, 15}, {22, -1, -5, 35}, {1206, 0, 2, 35}// 2	4	6	
			, {18, -1, 3, 15}, {1206, 0, 3, 25}, {23, -2, -5, 35}// 7	8	9	
			, {2861, 0, 3, 25}, {1206, 0, -2, 15}, {1206, 0, -3, 15}// 10	11	12	
			, {1206, -1, -2, 15}, {1206, 0, -4, 35}, {1206, -1, 3, 15}// 13	14	16	
			, {2440, -2, -3, 20}, {2866, -1, -4, 15}, {2765, -1, -2, 16}// 17	18	19	
			, {1206, 0, 3, 15}, {21, -2, 1, 35}, {1206, -1, -4, 15}// 20	21	22	
			, {21, -2, 2, 35}, {1206, -1, 1, 15}, {21, -2, -3, 35}// 23	24	25	
			, {1206, 0, -4, 15}, {2440, -2, 1, 20}, {8, -2, -4, 15}// 26	27	28	
			, {21, -2, -1, 35}, {1206, 0, -1, 35}, {1206, 0, 1, 35}// 29	30	31	
			, {21, -2, 0, 35}, {1206, -1, -1, 15}, {22, -1, 2, 35}// 32	33	35	
			, {1206, 0, 0, 15}, {7, -1, 2, 15}, {1206, -1, 3, 25}// 36	37	38	
			, {22, 0, -5, 35}, {7, 0, -5, 15}, {7, -1, -5, 15}// 39	40	41	
			, {2759, 0, -2, 16}, {2765, -1, -1, 16}, {1206, -1, 2, 15}// 42	43	44	
			, {8, -2, -2, 15}, {2759, 0, -1, 16}, {2768, 0, 0, 16}// 45	46	47	
			, {1206, -1, -3, 15}, {1206, 0, 0, 35}, {1206, -1, -4, 35}// 48	49	51	
			, {1206, -1, -1, 35}, {9, -2, -5, 15}, {2866, 0, -4, 15}// 52	53	54	
			, {1206, -1, 0, 15}, {1206, 0, 2, 15}, {1206, 0, -2, 35}// 55	56	57	
			, {1206, -1, -2, 35}, {18, 0, 3, 15}, {1206, -1, -3, 35}// 58	59	60	
			, {8, -2, 0, 15}, {22, 0, 2, 35}, {21, -2, -2, 35}// 61	62	63	
			, {17, -2, 3, 15}, {21, -2, -4, 35}, {1206, -1, 0, 35}// 64	65	67	
			, {1206, -1, 1, 35}, {1206, -1, 2, 35}, {1206, 0, -3, 35}// 68	69	70	
			, {2762, -1, -3, 16}, {7, 0, 2, 15}, {2763, -1, 0, 16}// 71	72	73	
			, {13, -2, 2, 15}, {2766, 0, -3, 16}, {1206, 2, -3, 35}// 75	76	77	
			, {1206, 3, -1, 35}, {1206, 2, -4, 35}, {1206, 1, -1, 35}// 78	79	80	
			, {2768, 1, 0, 16}, {2866, 1, -4, 15}, {21, 3, -2, 35}// 81	82	83	
			, {2861, 1, 3, 25}, {1206, 2, -2, 15}, {1206, 2, 3, 25}// 84	85	87	
			, {2759, 1, -1, 16}, {1206, 3, 0, 15}, {2767, 2, -1, 16}// 88	89	90	
			, {1206, 1, -4, 15}, {1206, 1, 3, 25}, {2759, 1, -2, 16}// 91	92	93	
			, {1206, 2, 3, 15}, {8, 3, -2, 15}, {1206, 2, 1, 35}// 94	95	96	
			, {1206, 3, -3, 15}, {1206, 1, -2, 35}, {7, 1, 2, 15}// 97	98	99	
			, {6, 3, 2, 15}, {18, 1, 3, 15}, {1206, 2, -1, 15}// 100	101	102	
			, {1206, 1, -3, 35}, {21, 3, 0, 35}, {1206, 2, -1, 35}// 103	104	105	
			, {1206, 2, -3, 15}, {7, 2, 2, 15}, {1206, 2, 2, 15}// 106	107	109	
			, {22, 1, 2, 35}, {21, 3, 1, 35}, {1206, 2, -2, 35}// 111	112	113	
			, {1206, 3, -2, 15}, {1206, 2, -4, 15}, {1206, 2, 0, 15}// 114	115	117	
			, {1206, 3, 0, 35}, {1206, 3, -3, 35}, {1206, 2, 2, 35}// 118	119	120	
			, {2764, 2, -3, 16}, {1206, 1, 2, 15}, {22, 3, -5, 35}// 121	122	123	
			, {18, 2, 3, 15}, {2767, 2, -2, 16}, {2861, 2, 3, 25}// 124	125	126	
			, {12, 3, -5, 15}, {1206, 1, -3, 15}, {22, 2, 2, 35}// 127	128	129	
			, {20, 3, 2, 35}, {1206, 3, 1, 15}, {7, 1, -5, 15}// 130	132	133	
			, {21, 3, -1, 35}, {1206, 1, 1, 15}, {1206, 3, 2, 15}// 134	135	136	
			, {2761, 2, 0, 16}, {1206, 3, -1, 15}, {1206, 2, 1, 15}// 137	138	139	
			, {2866, 2, -4, 15}, {22, 2, -5, 35}, {1206, 3, -4, 35}// 141	142	143	
			, {1206, 3, -4, 15}, {1206, 3, 3, 15}, {1206, 1, 3, 15}// 144	145	146	
			, {7, 2, -5, 15}, {1206, 3, -2, 35}, {22, 1, -5, 35}// 147	148	149	
			, {21, 3, -4, 35}, {1206, 1, 0, 15}, {1206, 1, -4, 35}// 150	153	154	
			, {1206, 2, 0, 35}, {1206, 1, 0, 35}, {1206, 1, 1, 35}// 155	156	157	
			, {1206, 1, 2, 35}, {8, 3, 0, 15}, {1206, 3, 3, 25}// 158	159	160	
			, {21, 3, -3, 35}, {16, 3, 3, 15}, {8, 3, -4, 15}// 161	162	163	
			, {1206, 3, 1, 35}, {1206, 3, 2, 35}, {2766, 1, -3, 16}// 164	165	166	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RoyalCarriageAddonDeed();
			}
		}

		[ Constructable ]
		public RoyalCarriageAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2594, -1, 4, 25, 0, 29, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2557, -1, 0, 25, 0, 8, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5112, -1, 4, 10, 0, -1, "harness", 1);// 5
			AddComplexComponent( (BaseAddon) this, 5522, 0, -4, 16, 38, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 15, -2, -3, 15, 0, 0, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 5112, -1, 5, 10, 0, -1, "harness", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2557, -1, -2, 25, 0, 8, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 15, -2, 1, 15, 0, 0, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 5112, 1, 5, 10, 0, -1, "harness", 1);// 86
			AddComplexComponent( (BaseAddon) this, 5112, 1, 3, 10, 0, -1, "harness", 1);// 108
			AddComplexComponent( (BaseAddon) this, 15, 3, -3, 15, 0, 0, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 2594, 3, 4, 25, 0, 29, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 3693, 2, -4, 0, 1717, -1, "wheel", 1);// 131
			AddComplexComponent( (BaseAddon) this, 3693, 2, 1, 0, 1717, -1, "wheel", 1);// 140
			AddComplexComponent( (BaseAddon) this, 15, 3, 1, 15, 0, 0, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 5523, 1, -4, 16, 38, -1, "", 1);// 152

		}

		public RoyalCarriageAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RoyalCarriageAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RoyalCarriageAddon();
			}
		}

		[Constructable]
		public RoyalCarriageAddonDeed()
		{
			Name = "RoyalCarriage";
		}

		public RoyalCarriageAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}