
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmolderingRubbleAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmolderingRubbleAddonDeed();
			}
		}

		[ Constructable ]
		public SmolderingRubbleAddon()
		{



			AddComplexComponent( (BaseAddon) this, 7083, 0, -1, 0, 2075, -1, "smoldering rubble", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7081, -1, -2, 0, 2075, -1, "smoldering rubble", 1);// 2
			AddComplexComponent( (BaseAddon) this, 7082, 0, -2, 0, 2075, -1, "smoldering rubble", 1);// 3
			AddComplexComponent( (BaseAddon) this, 7084, 1, -1, 0, 2075, -1, "smoldering rubble", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7085, 1, -2, 0, 2075, -1, "smoldering rubble", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7079, -1, 0, 0, 2075, -1, "smoldering rubble", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7077, -2, -1, 0, 2075, -1, "smoldering rubble", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7076, -2, 0, 0, 2075, -1, "smoldering rubble", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7080, -1, -1, 0, 2075, -1, "smoldering rubble", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7073, -1, 2, 0, 2075, -1, "smoldering rubble", 1);// 10
			AddComplexComponent( (BaseAddon) this, 7078, -1, 1, 0, 2075, -1, "smoldering rubble", 1);// 11
			AddComplexComponent( (BaseAddon) this, 7090, 1, 1, 0, 2075, -1, "smoldering rubble", 1);// 12
			AddComplexComponent( (BaseAddon) this, 7071, 1, 2, 0, 2075, -1, "smoldering rubble", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7074, -2, 2, 0, 2075, -1, "smoldering rubble", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7075, -2, 1, 0, 2075, -1, "smoldering rubble", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7072, 0, 2, 0, 2075, -1, "smoldering rubble", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7086, 2, -2, 0, 2075, -1, "smoldering rubble", 1);// 17
			AddComplexComponent( (BaseAddon) this, 7087, 2, -1, 0, 2075, -1, "smoldering rubble", 1);// 18
			AddComplexComponent( (BaseAddon) this, 7088, 2, 0, 0, 2075, -1, "smoldering rubble", 1);// 19
			AddComplexComponent( (BaseAddon) this, 7089, 2, 1, 0, 2075, -1, "smoldering rubble", 1);// 20

		}

		public SmolderingRubbleAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmolderingRubbleAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmolderingRubbleAddon();
			}
		}

		[Constructable]
		public SmolderingRubbleAddonDeed()
		{
			Name = "SmolderingRubble";
		}

		public SmolderingRubbleAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}