
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DisplayCase1x4Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2822, 0, 2, 0}, {2823, 0, 1, 0}, {2823, 0, 0, 0}// 1	2	3	
			, {2819, 0, 2, 3}, {2820, 0, 1, 3}, {2824, 0, -1, 0}// 4	5	6	
			, {2820, 0, 0, 3}, {2821, 0, -1, 3}// 7	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DisplayCase1x4AddonDeed();
			}
		}

		[ Constructable ]
		public DisplayCase1x4Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public DisplayCase1x4Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DisplayCase1x4AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DisplayCase1x4Addon();
			}
		}

		[Constructable]
		public DisplayCase1x4AddonDeed()
		{
			Name = "Display Case 1x4";
		}

		public DisplayCase1x4AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}